name = "atcf_hardware_basic_grip"
doc="""
This repository is for building, testing and running some of the basic ATCF CDL hardware.

It requires ATCF_CDL_TOOLS_PATH to point to an ATCF CDL tools grip directory configured with at least grip and CDL.
Hence $(ATCF_CDL_TOOLS_PATH)/tools/bin/cdl will be the cdl tool, and $(ATCF_CDL_TOOLS_PATH)/grip/grip will be the grip tool.

"""
default_config="all"
configs         = ["all"]
base_repos=["atcf_hardware_std", "atcf_hardware_apb", "atcf_hardware_utils", "atcf_hardware_video", "atcf_hardware_io"]
workflow="single"
stages=["clean", "build", "smoke"]
logging         = "Yes"

[env]
PATH="@ATCF_CDL_TOOLS_PATH@/tools/bin:@ATCF_CDL_TOOLS_PATH@/grip:@PATH@"
BUILD_DIR="@GRIP_ROOT_PATH@/build"
ATCF_CDL_TOOLS_PATH="@ATCF_CDL_TOOLS_PATH@"
CDL_ROOT="@ATCF_CDL_TOOLS_PATH@/tools"
VERILATOR_ROOT="@ATCF_CDL_TOOLS_PATH@/tools"
VERILATOR_SHARE="@ATCF_CDL_TOOLS_PATH@/tools/share/verilator"

[config.all]

[config.all.env]
SRC_ROOT     = "@GRIP_ROOT_PATH@/atcf_hardware_video @GRIP_ROOT_PATH@/atcf_hardware_utils"
MAKE_OPTIONS = "-f @GRIP_ROOT_PATH@/atcf_hardware_video/Makefile SRC_ROOT='@SRC_ROOT@' BUILD_ROOT=@BUILD_DIR@"

[config.all.stage.clean_all_sim]
exec="mkdir -p @BUILD_DIR@ && cd @BUILD_DIR@ && make @MAKE_OPTIONS@ clean"

[config.all.stage.build]
requires=["clean_all_sim"]
wd="@BUILD_DIR@"
exec="make @MAKE_OPTIONS@ -j8 all"

[config.all.stage.smoke]
action="yes"

[repo.atcf_hardware_std]
url="https://github.com/atthecodeface/atcf_hardware_std.git"
branch="master"
path="atcf_hardware_std"
smoke_test.satisfies="smoke"

[repo.atcf_hardware_utils]
url="https://github.com/atthecodeface/atcf_hardware_utils.git"
branch="master"
path="atcf_hardware_utils"
smoke_test.satisfies="smoke"

[repo.atcf_hardware_io]
url="https://github.com/atthecodeface/atcf_hardware_io.git"
branch="master"
path="atcf_hardware_io"

[repo.atcf_hardware_video]
url="https://github.com/atthecodeface/atcf_hardware_video.git"
branch="master"
path="atcf_hardware_video"
smoke_test.satisfies="smoke"

[repo.atcf_hardware_apb]
url="https://github.com/atthecodeface/atcf_hardware_apb.git"
branch="master"
path="atcf_hardware_apb"
smoke_test.satisfies="smoke"

