[all.atcf_hardware_std]
changeset = "fba77e7de21da7092d7c14bedc806764572b4d2a"
branch = "master"

[all.atcf_hardware_apb]
changeset = "f679bdd0e4cab20cde03dd750da16cbdc6bf46e3"
branch = "master"

[all.atcf_hardware_utils]
changeset = "bcfdd29ecb880afff7834306a9dd7e15a8c2c32b"
branch = "master"

[all.atcf_hardware_video]
changeset = "eaab5a2513991b9e26ab50ffc2abefd89d041913"
branch = "master"

[all.atcf_hardware_io]
changeset = "bc3cac7caa5bdd1cb944755e8683c576041b64db"
branch = "master"
