[all.atcf_hardware_std]
changeset = "7870bdfcbd39bca42e3ef63073ee4e628656fa6a"
branch = "master"

[all.atcf_hardware_apb]
changeset = "58b3b8bae7cb602042c43e3f361a56b2853f85f1"
branch = "master"

[all.atcf_hardware_utils]
changeset = "94af5cf5ac93d5b3155967f1c5ca7833dd01ef73"
branch = "master"

[all.atcf_hardware_video]
changeset = "d6f8bdd1eddf5394c01291d3d116da49fc1096f4"
branch = "master"

[all.atcf_hardware_io]
changeset = "bf86eb7c7ae03be190718a583dbda901bdac799a"
branch = "master"
